# Generated by jeolm.makefile for TargetNode(name='ultimate')

ultimate: | \
  2014-summer-istra-Integral.pdf \
  build/documents/Integral/main.pdf
.PHONY: ultimate

2014-summer-istra-Integral.pdf: | \
  build/documents/Integral/main.pdf
	ln --symbolic --force "build/documents/Integral/main.pdf" "$@"

build/documents/Integral/main.pdf: \
  build/documents/Integral/Integral.dvi \
  build/figures/combinatorics-painting-g9-t-tetramino/main.eps \
  build/figures/combinatorics-invariant-g9-signes/main.eps \
  build/figures/combinatorics-invariant-g9-rooks/main.eps \
  build/figures/combinatorics-semi-invariant-g9-signes-1/main.eps \
  build/figures/combinatorics-semi-invariant-g9-signes-2/main.eps \
  build/figures/combinatorics-graph-planar-petersen/main.eps \
  | \
  build/documents/Integral/combinatorics-painting-g9-t-tetramino.eps \
  build/documents/Integral/combinatorics-invariant-g9-signes.eps \
  build/documents/Integral/combinatorics-invariant-g9-rooks.eps \
  build/documents/Integral/combinatorics-semi-invariant-g9-signes-1.eps \
  build/documents/Integral/combinatorics-semi-invariant-g9-signes-2.eps \
  build/documents/Integral/combinatorics-graph-planar-petersen.eps
	cd "build/documents/Integral" && "dvipdf" "Integral.dvi" "main.pdf"

build/documents/Integral/Integral.dvi: \
  build/documents/Integral/main.tex \
  build/packages/_style-jeolm/jeolm.sty \
  build/figures/combinatorics-painting-g9-t-tetramino/main.eps \
  build/figures/combinatorics-invariant-g9-signes/main.eps \
  build/figures/combinatorics-invariant-g9-rooks/main.eps \
  build/figures/combinatorics-semi-invariant-g9-signes-1/main.eps \
  build/figures/combinatorics-semi-invariant-g9-signes-2/main.eps \
  build/figures/combinatorics-graph-planar-petersen/main.eps \
  source/integral.tex \
  source/olympiad/g78-n1.tex \
  source/olympiad/g9.tex \
  source/olympiad/g1011.tex \
  source/olympiad/g10.tex \
  source/olympiad/g11.tex \
  source/olympiad/g78-n2.tex \
  source/algebra/progression-g78r2.tex \
  source/algebra/fibbonaci.tex \
  source/algebra/quadratic-trinomial-g9.tex \
  source/algebra/quadratic-trinomial-g9-more.tex \
  source/algebra/quadratic-trinomial-g1011.tex \
  source/algebra/mixture-g1011.tex \
  source/algebra/polynomial-w-integer-coeff-g1011.tex \
  source/algebra/polynomial-chinese-remainder-theorem.tex \
  source/algebra/polynomial-interpolation.tex \
  source/algebra/generating-function.tex \
  source/algebra/fundamental-theorem.tex \
  source/algebra/mixture-g11.tex \
  source/algebra/inequality/mean-g78r2.tex \
  source/algebra/inequality/mean-g9.tex \
  source/algebra/inequality/smoothing.tex \
  source/algebra/inequality/mixture-g1011.tex \
  source/algebra/inequality/jensen.tex \
  source/algebra/inequality/mixture-g11.tex \
  source/algebra/number-theory/modular-arithmetic-g78/r2-1.tex \
  source/algebra/number-theory/modular-arithmetic-g78/r2-2.tex \
  source/algebra/number-theory/modular-arithmetic-g78/r1-1.tex \
  source/algebra/number-theory/modular-arithmetic-g78/r1-2.tex \
  source/algebra/number-theory/mixture-g78r2.tex \
  source/algebra/number-theory/exponent-g78r1.tex \
  source/algebra/number-theory/diophantine-equations-g78r1.tex \
  source/algebra/number-theory/euler-function-g78r1.tex \
  source/algebra/number-theory/divisibility-g9.tex \
  source/algebra/number-theory/mixture-g9.tex \
  source/algebra/number-theory/euler-function-g1011.tex \
  source/algebra/number-theory/mixture-g1011.tex \
  source/algebra/number-theory/chinese-remainder-theorem.tex \
  source/algebra/number-theory/mixture-g10.tex \
  source/algebra/number-theory/mixture-g11.tex \
  source/geometry/triangle-inequality.tex \
  source/geometry/equal-triangles-g78r2.tex \
  source/geometry/inequality-g78r2.tex \
  source/geometry/combinatorial-g78r2.tex \
  source/geometry/mixture-g78r1-intro.tex \
  source/geometry/inscribed-angle-g78r1/1.tex \
  source/geometry/inscribed-angle-g78r1/2.tex \
  source/geometry/mixture-g78r1.tex \
  source/geometry/combinatorial-g78r1.tex \
  source/geometry/right-triangle-g9.tex \
  source/geometry/locus-g9.tex \
  source/geometry/radical-axis.tex \
  source/geometry/combinatorial-g9.tex \
  source/geometry/mixture-g1011-1.tex \
  source/geometry/mixture-g1011-2.tex \
  source/geometry/mixture-g1011-appendage.tex \
  source/geometry/orthocenter-g1011.tex \
  source/geometry/mass-point/1.tex \
  source/geometry/mass-point/2.tex \
  source/geometry/mass-point/3.tex \
  source/geometry/simson-line-g10.tex \
  source/geometry/euler-line/g1011.tex \
  source/geometry/euler-line/g10.tex \
  source/geometry/projective-g11/basics.tex \
  source/geometry/projective-g11/circle.tex \
  source/geometry/polar-line-g11.tex \
  source/geometry/sparrows/1.tex \
  source/geometry/sparrows/2.tex \
  source/combinatorics/search-g78r2.tex \
  source/combinatorics/weighing-g78r2.tex \
  source/combinatorics/algorithm-g78r2.tex \
  source/combinatorics/counting-g78r2/1.tex \
  source/combinatorics/counting-g78r2/2.tex \
  source/combinatorics/inclusion-exclusion-g78r2.tex \
  source/combinatorics/logic-g78r2.tex \
  source/combinatorics/mixture-g78r2.tex \
  source/combinatorics/extreme-principle-g78r2.tex \
  source/combinatorics/game-g78r1/joke.tex \
  source/combinatorics/game-g78r1/symmetry.tex \
  source/combinatorics/game-g78r1/sum.tex \
  source/combinatorics/game-g78r1/chase.tex \
  source/combinatorics/game-g78r1/win-position.tex \
  source/combinatorics/game-g78r1/mixture.tex \
  source/combinatorics/weighing-g78r1.tex \
  source/combinatorics/information-g78r1.tex \
  source/combinatorics/painting-g9.tex \
  source/combinatorics/invariant-g9.tex \
  source/combinatorics/semi-invariant-g9.tex \
  source/combinatorics/constructive-g9.tex \
  source/combinatorics/infinity-g9/1.tex \
  source/combinatorics/infinity-g9/2.tex \
  source/combinatorics/game-g9.tex \
  source/combinatorics/geometric-g9.tex \
  source/combinatorics/recurrent-g10/loop.tex \
  source/combinatorics/recurrent-g10/one-dimension.tex \
  source/combinatorics/recurrent-g10/fibbonaci.tex \
  source/combinatorics/recurrent-g10/binomial.tex \
  source/combinatorics/recurrent-g10/catalan.tex \
  source/combinatorics/game-g1011.tex \
  source/combinatorics/semi-invariant-g1011.tex \
  source/combinatorics/counting-g1011.tex \
  source/combinatorics/game-g11.tex \
  source/combinatorics/invariant-g11.tex \
  source/combinatorics/semi-invariant-g11.tex \
  source/combinatorics/graph/g78r2/basics.tex \
  source/combinatorics/graph/g78r2/bipartite.tex \
  source/combinatorics/graph/g78r2/oriented.tex \
  source/combinatorics/graph/g1011/mixture.tex \
  source/combinatorics/graph/g1011/oriented.tex \
  source/combinatorics/graph/planar.tex \
  source/combinatorics/graph/painting/1.tex \
  source/combinatorics/graph/painting/2.tex \
  source/combinatorics/graph/mixture-g11.tex \
  | \
  build/documents/Integral/jeolm.sty \
  build/documents/Integral/combinatorics-painting-g9-t-tetramino.eps \
  build/documents/Integral/combinatorics-invariant-g9-signes.eps \
  build/documents/Integral/combinatorics-invariant-g9-rooks.eps \
  build/documents/Integral/combinatorics-semi-invariant-g9-signes-1.eps \
  build/documents/Integral/combinatorics-semi-invariant-g9-signes-2.eps \
  build/documents/Integral/combinatorics-graph-planar-petersen.eps \
  build/documents/Integral/integral.in.tex \
  build/documents/Integral/olympiad-g78-n1.in.tex \
  build/documents/Integral/olympiad-g9.in.tex \
  build/documents/Integral/olympiad-g1011.in.tex \
  build/documents/Integral/olympiad-g10.in.tex \
  build/documents/Integral/olympiad-g11.in.tex \
  build/documents/Integral/olympiad-g78-n2.in.tex \
  build/documents/Integral/algebra-progression-g78r2.in.tex \
  build/documents/Integral/algebra-fibbonaci.in.tex \
  build/documents/Integral/algebra-quadratic-trinomial-g9.in.tex \
  build/documents/Integral/algebra-quadratic-trinomial-g9-more.in.tex \
  build/documents/Integral/algebra-quadratic-trinomial-g1011.in.tex \
  build/documents/Integral/algebra-mixture-g1011.in.tex \
  build/documents/Integral/algebra-polynomial-w-integer-coeff-g1011.in.tex \
  build/documents/Integral/algebra-polynomial-chinese-remainder-theorem.in.tex \
  build/documents/Integral/algebra-polynomial-interpolation.in.tex \
  build/documents/Integral/algebra-generating-function.in.tex \
  build/documents/Integral/algebra-fundamental-theorem.in.tex \
  build/documents/Integral/algebra-mixture-g11.in.tex \
  build/documents/Integral/algebra-inequality-mean-g78r2.in.tex \
  build/documents/Integral/algebra-inequality-mean-g9.in.tex \
  build/documents/Integral/algebra-inequality-smoothing.in.tex \
  build/documents/Integral/algebra-inequality-mixture-g1011.in.tex \
  build/documents/Integral/algebra-inequality-jensen.in.tex \
  build/documents/Integral/algebra-inequality-mixture-g11.in.tex \
  build/documents/Integral/algebra-number-theory-modular-arithmetic-g78-r2-1.in.tex \
  build/documents/Integral/algebra-number-theory-modular-arithmetic-g78-r2-2.in.tex \
  build/documents/Integral/algebra-number-theory-modular-arithmetic-g78-r1-1.in.tex \
  build/documents/Integral/algebra-number-theory-modular-arithmetic-g78-r1-2.in.tex \
  build/documents/Integral/algebra-number-theory-mixture-g78r2.in.tex \
  build/documents/Integral/algebra-number-theory-exponent-g78r1.in.tex \
  build/documents/Integral/algebra-number-theory-diophantine-equations-g78r1.in.tex \
  build/documents/Integral/algebra-number-theory-euler-function-g78r1.in.tex \
  build/documents/Integral/algebra-number-theory-divisibility-g9.in.tex \
  build/documents/Integral/algebra-number-theory-mixture-g9.in.tex \
  build/documents/Integral/algebra-number-theory-euler-function-g1011.in.tex \
  build/documents/Integral/algebra-number-theory-mixture-g1011.in.tex \
  build/documents/Integral/algebra-number-theory-chinese-remainder-theorem.in.tex \
  build/documents/Integral/algebra-number-theory-mixture-g10.in.tex \
  build/documents/Integral/algebra-number-theory-mixture-g11.in.tex \
  build/documents/Integral/geometry-triangle-inequality.in.tex \
  build/documents/Integral/geometry-equal-triangles-g78r2.in.tex \
  build/documents/Integral/geometry-inequality-g78r2.in.tex \
  build/documents/Integral/geometry-combinatorial-g78r2.in.tex \
  build/documents/Integral/geometry-mixture-g78r1-intro.in.tex \
  build/documents/Integral/geometry-inscribed-angle-g78r1-1.in.tex \
  build/documents/Integral/geometry-inscribed-angle-g78r1-2.in.tex \
  build/documents/Integral/geometry-mixture-g78r1.in.tex \
  build/documents/Integral/geometry-combinatorial-g78r1.in.tex \
  build/documents/Integral/geometry-right-triangle-g9.in.tex \
  build/documents/Integral/geometry-locus-g9.in.tex \
  build/documents/Integral/geometry-radical-axis.in.tex \
  build/documents/Integral/geometry-combinatorial-g9.in.tex \
  build/documents/Integral/geometry-mixture-g1011-1.in.tex \
  build/documents/Integral/geometry-mixture-g1011-2.in.tex \
  build/documents/Integral/geometry-mixture-g1011-appendage.in.tex \
  build/documents/Integral/geometry-orthocenter-g1011.in.tex \
  build/documents/Integral/geometry-mass-point-1.in.tex \
  build/documents/Integral/geometry-mass-point-2.in.tex \
  build/documents/Integral/geometry-mass-point-3.in.tex \
  build/documents/Integral/geometry-simson-line-g10.in.tex \
  build/documents/Integral/geometry-euler-line-g1011.in.tex \
  build/documents/Integral/geometry-euler-line-g10.in.tex \
  build/documents/Integral/geometry-projective-g11-basics.in.tex \
  build/documents/Integral/geometry-projective-g11-circle.in.tex \
  build/documents/Integral/geometry-polar-line-g11.in.tex \
  build/documents/Integral/geometry-sparrows-1.in.tex \
  build/documents/Integral/geometry-sparrows-2.in.tex \
  build/documents/Integral/combinatorics-search-g78r2.in.tex \
  build/documents/Integral/combinatorics-weighing-g78r2.in.tex \
  build/documents/Integral/combinatorics-algorithm-g78r2.in.tex \
  build/documents/Integral/combinatorics-counting-g78r2-1.in.tex \
  build/documents/Integral/combinatorics-counting-g78r2-2.in.tex \
  build/documents/Integral/combinatorics-inclusion-exclusion-g78r2.in.tex \
  build/documents/Integral/combinatorics-logic-g78r2.in.tex \
  build/documents/Integral/combinatorics-mixture-g78r2.in.tex \
  build/documents/Integral/combinatorics-extreme-principle-g78r2.in.tex \
  build/documents/Integral/combinatorics-game-g78r1-joke.in.tex \
  build/documents/Integral/combinatorics-game-g78r1-symmetry.in.tex \
  build/documents/Integral/combinatorics-game-g78r1-sum.in.tex \
  build/documents/Integral/combinatorics-game-g78r1-chase.in.tex \
  build/documents/Integral/combinatorics-game-g78r1-win-position.in.tex \
  build/documents/Integral/combinatorics-game-g78r1-mixture.in.tex \
  build/documents/Integral/combinatorics-weighing-g78r1.in.tex \
  build/documents/Integral/combinatorics-information-g78r1.in.tex \
  build/documents/Integral/combinatorics-painting-g9.in.tex \
  build/documents/Integral/combinatorics-invariant-g9.in.tex \
  build/documents/Integral/combinatorics-semi-invariant-g9.in.tex \
  build/documents/Integral/combinatorics-constructive-g9.in.tex \
  build/documents/Integral/combinatorics-infinity-g9-1.in.tex \
  build/documents/Integral/combinatorics-infinity-g9-2.in.tex \
  build/documents/Integral/combinatorics-game-g9.in.tex \
  build/documents/Integral/combinatorics-geometric-g9.in.tex \
  build/documents/Integral/combinatorics-recurrent-g10-loop.in.tex \
  build/documents/Integral/combinatorics-recurrent-g10-one-dimension.in.tex \
  build/documents/Integral/combinatorics-recurrent-g10-fibbonaci.in.tex \
  build/documents/Integral/combinatorics-recurrent-g10-binomial.in.tex \
  build/documents/Integral/combinatorics-recurrent-g10-catalan.in.tex \
  build/documents/Integral/combinatorics-game-g1011.in.tex \
  build/documents/Integral/combinatorics-semi-invariant-g1011.in.tex \
  build/documents/Integral/combinatorics-counting-g1011.in.tex \
  build/documents/Integral/combinatorics-game-g11.in.tex \
  build/documents/Integral/combinatorics-invariant-g11.in.tex \
  build/documents/Integral/combinatorics-semi-invariant-g11.in.tex \
  build/documents/Integral/combinatorics-graph-g78r2-basics.in.tex \
  build/documents/Integral/combinatorics-graph-g78r2-bipartite.in.tex \
  build/documents/Integral/combinatorics-graph-g78r2-oriented.in.tex \
  build/documents/Integral/combinatorics-graph-g1011-mixture.in.tex \
  build/documents/Integral/combinatorics-graph-g1011-oriented.in.tex \
  build/documents/Integral/combinatorics-graph-planar.in.tex \
  build/documents/Integral/combinatorics-graph-painting-1.in.tex \
  build/documents/Integral/combinatorics-graph-painting-2.in.tex \
  build/documents/Integral/combinatorics-graph-mixture-g11.in.tex
	cd "build/documents/Integral" && "latex" "-jobname=Integral" "-interaction=nonstopmode" "-halt-on-error" "-file-line-error" "main.tex"

build/documents/Integral:
	mkdir --parents "$@"

build/documents/Integral/jeolm.sty: | \
  build/packages/_style-jeolm/jeolm.sty \
  build/documents/Integral
	ln --symbolic --force "../../packages/_style-jeolm/jeolm.sty" "$@"

build/packages/_style-jeolm/jeolm.sty: \
  source/_style/jeolm.dtx \
  build/packages/_style-jeolm/package.ins \
  | \
  build/packages/_style-jeolm \
  build/packages/_style-jeolm/jeolm.dtx
	cd "build/packages/_style-jeolm" && "latex" "-interaction=nonstopmode" "-halt-on-error" "-file-line-error" "package.ins"

build/packages/_style-jeolm:
	mkdir --parents "$@"

build/packages/_style-jeolm/jeolm.dtx: | \
  source/_style/jeolm.dtx \
  build/packages/_style-jeolm
	ln --symbolic --force "../../../source/_style/jeolm.dtx" "$@"

build/documents/Integral/combinatorics-painting-g9-t-tetramino.eps: | \
  build/figures/combinatorics-painting-g9-t-tetramino/main.eps \
  build/documents/Integral
	ln --symbolic --force "../../figures/combinatorics-painting-g9-t-tetramino/main.eps" "$@"

build/figures/combinatorics-painting-g9-t-tetramino/main.eps: \
  source/combinatorics/painting-g9/t-tetramino.asy \
  | \
  build/figures/combinatorics-painting-g9-t-tetramino/main.asy \
  build/figures/combinatorics-painting-g9-t-tetramino
	cd "build/figures/combinatorics-painting-g9-t-tetramino" && "asy" "-outformat=eps" "-offscreen" "main.asy"

build/figures/combinatorics-painting-g9-t-tetramino/main.asy: | \
  source/combinatorics/painting-g9/t-tetramino.asy \
  build/figures/combinatorics-painting-g9-t-tetramino
	ln --symbolic --force "../../../source/combinatorics/painting-g9/t-tetramino.asy" "$@"

build/figures/combinatorics-painting-g9-t-tetramino:
	mkdir --parents "$@"

build/documents/Integral/combinatorics-invariant-g9-signes.eps: | \
  build/figures/combinatorics-invariant-g9-signes/main.eps \
  build/documents/Integral
	ln --symbolic --force "../../figures/combinatorics-invariant-g9-signes/main.eps" "$@"

build/figures/combinatorics-invariant-g9-signes/main.eps: \
  source/combinatorics/invariant-g9/signes.asy \
  | \
  build/figures/combinatorics-invariant-g9-signes/main.asy \
  build/figures/combinatorics-invariant-g9-signes
	cd "build/figures/combinatorics-invariant-g9-signes" && "asy" "-outformat=eps" "-offscreen" "main.asy"

build/figures/combinatorics-invariant-g9-signes/main.asy: | \
  source/combinatorics/invariant-g9/signes.asy \
  build/figures/combinatorics-invariant-g9-signes
	ln --symbolic --force "../../../source/combinatorics/invariant-g9/signes.asy" "$@"

build/figures/combinatorics-invariant-g9-signes:
	mkdir --parents "$@"

build/documents/Integral/combinatorics-invariant-g9-rooks.eps: | \
  build/figures/combinatorics-invariant-g9-rooks/main.eps \
  build/documents/Integral
	ln --symbolic --force "../../figures/combinatorics-invariant-g9-rooks/main.eps" "$@"

build/figures/combinatorics-invariant-g9-rooks/main.eps: \
  source/combinatorics/invariant-g9/rooks.asy \
  | \
  build/figures/combinatorics-invariant-g9-rooks/main.asy \
  build/figures/combinatorics-invariant-g9-rooks
	cd "build/figures/combinatorics-invariant-g9-rooks" && "asy" "-outformat=eps" "-offscreen" "main.asy"

build/figures/combinatorics-invariant-g9-rooks/main.asy: | \
  source/combinatorics/invariant-g9/rooks.asy \
  build/figures/combinatorics-invariant-g9-rooks
	ln --symbolic --force "../../../source/combinatorics/invariant-g9/rooks.asy" "$@"

build/figures/combinatorics-invariant-g9-rooks:
	mkdir --parents "$@"

build/documents/Integral/combinatorics-semi-invariant-g9-signes-1.eps: | \
  build/figures/combinatorics-semi-invariant-g9-signes-1/main.eps \
  build/documents/Integral
	ln --symbolic --force "../../figures/combinatorics-semi-invariant-g9-signes-1/main.eps" "$@"

build/figures/combinatorics-semi-invariant-g9-signes-1/main.eps: \
  source/combinatorics/semi-invariant-g9/signes-1.asy \
  | \
  build/figures/combinatorics-semi-invariant-g9-signes-1/main.asy \
  build/figures/combinatorics-semi-invariant-g9-signes-1
	cd "build/figures/combinatorics-semi-invariant-g9-signes-1" && "asy" "-outformat=eps" "-offscreen" "main.asy"

build/figures/combinatorics-semi-invariant-g9-signes-1/main.asy: | \
  source/combinatorics/semi-invariant-g9/signes-1.asy \
  build/figures/combinatorics-semi-invariant-g9-signes-1
	ln --symbolic --force "../../../source/combinatorics/semi-invariant-g9/signes-1.asy" "$@"

build/figures/combinatorics-semi-invariant-g9-signes-1:
	mkdir --parents "$@"

build/documents/Integral/combinatorics-semi-invariant-g9-signes-2.eps: | \
  build/figures/combinatorics-semi-invariant-g9-signes-2/main.eps \
  build/documents/Integral
	ln --symbolic --force "../../figures/combinatorics-semi-invariant-g9-signes-2/main.eps" "$@"

build/figures/combinatorics-semi-invariant-g9-signes-2/main.eps: \
  source/combinatorics/semi-invariant-g9/signes-2.asy \
  | \
  build/figures/combinatorics-semi-invariant-g9-signes-2/main.asy \
  build/figures/combinatorics-semi-invariant-g9-signes-2
	cd "build/figures/combinatorics-semi-invariant-g9-signes-2" && "asy" "-outformat=eps" "-offscreen" "main.asy"

build/figures/combinatorics-semi-invariant-g9-signes-2/main.asy: | \
  source/combinatorics/semi-invariant-g9/signes-2.asy \
  build/figures/combinatorics-semi-invariant-g9-signes-2
	ln --symbolic --force "../../../source/combinatorics/semi-invariant-g9/signes-2.asy" "$@"

build/figures/combinatorics-semi-invariant-g9-signes-2:
	mkdir --parents "$@"

build/documents/Integral/combinatorics-graph-planar-petersen.eps: | \
  build/figures/combinatorics-graph-planar-petersen/main.eps \
  build/documents/Integral
	ln --symbolic --force "../../figures/combinatorics-graph-planar-petersen/main.eps" "$@"

build/figures/combinatorics-graph-planar-petersen/main.eps: \
  source/combinatorics/graph/planar/petersen.asy \
  | \
  build/figures/combinatorics-graph-planar-petersen/main.asy \
  build/figures/combinatorics-graph-planar-petersen
	cd "build/figures/combinatorics-graph-planar-petersen" && "asy" "-outformat=eps" "-offscreen" "main.asy"

build/figures/combinatorics-graph-planar-petersen/main.asy: | \
  source/combinatorics/graph/planar/petersen.asy \
  build/figures/combinatorics-graph-planar-petersen
	ln --symbolic --force "../../../source/combinatorics/graph/planar/petersen.asy" "$@"

build/figures/combinatorics-graph-planar-petersen:
	mkdir --parents "$@"

build/documents/Integral/integral.in.tex: | \
  source/integral.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/integral.tex" "$@"

build/documents/Integral/olympiad-g78-n1.in.tex: | \
  source/olympiad/g78-n1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/olympiad/g78-n1.tex" "$@"

build/documents/Integral/olympiad-g9.in.tex: | \
  source/olympiad/g9.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/olympiad/g9.tex" "$@"

build/documents/Integral/olympiad-g1011.in.tex: | \
  source/olympiad/g1011.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/olympiad/g1011.tex" "$@"

build/documents/Integral/olympiad-g10.in.tex: | \
  source/olympiad/g10.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/olympiad/g10.tex" "$@"

build/documents/Integral/olympiad-g11.in.tex: | \
  source/olympiad/g11.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/olympiad/g11.tex" "$@"

build/documents/Integral/olympiad-g78-n2.in.tex: | \
  source/olympiad/g78-n2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/olympiad/g78-n2.tex" "$@"

build/documents/Integral/algebra-progression-g78r2.in.tex: | \
  source/algebra/progression-g78r2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/progression-g78r2.tex" "$@"

build/documents/Integral/algebra-fibbonaci.in.tex: | \
  source/algebra/fibbonaci.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/fibbonaci.tex" "$@"

build/documents/Integral/algebra-quadratic-trinomial-g9.in.tex: | \
  source/algebra/quadratic-trinomial-g9.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/quadratic-trinomial-g9.tex" "$@"

build/documents/Integral/algebra-quadratic-trinomial-g9-more.in.tex: | \
  source/algebra/quadratic-trinomial-g9-more.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/quadratic-trinomial-g9-more.tex" "$@"

build/documents/Integral/algebra-quadratic-trinomial-g1011.in.tex: | \
  source/algebra/quadratic-trinomial-g1011.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/quadratic-trinomial-g1011.tex" "$@"

build/documents/Integral/algebra-mixture-g1011.in.tex: | \
  source/algebra/mixture-g1011.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/mixture-g1011.tex" "$@"

build/documents/Integral/algebra-polynomial-w-integer-coeff-g1011.in.tex: | \
  source/algebra/polynomial-w-integer-coeff-g1011.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/polynomial-w-integer-coeff-g1011.tex" "$@"

build/documents/Integral/algebra-polynomial-chinese-remainder-theorem.in.tex: | \
  source/algebra/polynomial-chinese-remainder-theorem.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/polynomial-chinese-remainder-theorem.tex" "$@"

build/documents/Integral/algebra-polynomial-interpolation.in.tex: | \
  source/algebra/polynomial-interpolation.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/polynomial-interpolation.tex" "$@"

build/documents/Integral/algebra-generating-function.in.tex: | \
  source/algebra/generating-function.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/generating-function.tex" "$@"

build/documents/Integral/algebra-fundamental-theorem.in.tex: | \
  source/algebra/fundamental-theorem.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/fundamental-theorem.tex" "$@"

build/documents/Integral/algebra-mixture-g11.in.tex: | \
  source/algebra/mixture-g11.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/mixture-g11.tex" "$@"

build/documents/Integral/algebra-inequality-mean-g78r2.in.tex: | \
  source/algebra/inequality/mean-g78r2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/inequality/mean-g78r2.tex" "$@"

build/documents/Integral/algebra-inequality-mean-g9.in.tex: | \
  source/algebra/inequality/mean-g9.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/inequality/mean-g9.tex" "$@"

build/documents/Integral/algebra-inequality-smoothing.in.tex: | \
  source/algebra/inequality/smoothing.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/inequality/smoothing.tex" "$@"

build/documents/Integral/algebra-inequality-mixture-g1011.in.tex: | \
  source/algebra/inequality/mixture-g1011.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/inequality/mixture-g1011.tex" "$@"

build/documents/Integral/algebra-inequality-jensen.in.tex: | \
  source/algebra/inequality/jensen.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/inequality/jensen.tex" "$@"

build/documents/Integral/algebra-inequality-mixture-g11.in.tex: | \
  source/algebra/inequality/mixture-g11.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/inequality/mixture-g11.tex" "$@"

build/documents/Integral/algebra-number-theory-modular-arithmetic-g78-r2-1.in.tex: | \
  source/algebra/number-theory/modular-arithmetic-g78/r2-1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/modular-arithmetic-g78/r2-1.tex" "$@"

build/documents/Integral/algebra-number-theory-modular-arithmetic-g78-r2-2.in.tex: | \
  source/algebra/number-theory/modular-arithmetic-g78/r2-2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/modular-arithmetic-g78/r2-2.tex" "$@"

build/documents/Integral/algebra-number-theory-modular-arithmetic-g78-r1-1.in.tex: | \
  source/algebra/number-theory/modular-arithmetic-g78/r1-1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/modular-arithmetic-g78/r1-1.tex" "$@"

build/documents/Integral/algebra-number-theory-modular-arithmetic-g78-r1-2.in.tex: | \
  source/algebra/number-theory/modular-arithmetic-g78/r1-2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/modular-arithmetic-g78/r1-2.tex" "$@"

build/documents/Integral/algebra-number-theory-mixture-g78r2.in.tex: | \
  source/algebra/number-theory/mixture-g78r2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/mixture-g78r2.tex" "$@"

build/documents/Integral/algebra-number-theory-exponent-g78r1.in.tex: | \
  source/algebra/number-theory/exponent-g78r1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/exponent-g78r1.tex" "$@"

build/documents/Integral/algebra-number-theory-diophantine-equations-g78r1.in.tex: | \
  source/algebra/number-theory/diophantine-equations-g78r1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/diophantine-equations-g78r1.tex" "$@"

build/documents/Integral/algebra-number-theory-euler-function-g78r1.in.tex: | \
  source/algebra/number-theory/euler-function-g78r1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/euler-function-g78r1.tex" "$@"

build/documents/Integral/algebra-number-theory-divisibility-g9.in.tex: | \
  source/algebra/number-theory/divisibility-g9.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/divisibility-g9.tex" "$@"

build/documents/Integral/algebra-number-theory-mixture-g9.in.tex: | \
  source/algebra/number-theory/mixture-g9.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/mixture-g9.tex" "$@"

build/documents/Integral/algebra-number-theory-euler-function-g1011.in.tex: | \
  source/algebra/number-theory/euler-function-g1011.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/euler-function-g1011.tex" "$@"

build/documents/Integral/algebra-number-theory-mixture-g1011.in.tex: | \
  source/algebra/number-theory/mixture-g1011.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/mixture-g1011.tex" "$@"

build/documents/Integral/algebra-number-theory-chinese-remainder-theorem.in.tex: | \
  source/algebra/number-theory/chinese-remainder-theorem.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/chinese-remainder-theorem.tex" "$@"

build/documents/Integral/algebra-number-theory-mixture-g10.in.tex: | \
  source/algebra/number-theory/mixture-g10.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/mixture-g10.tex" "$@"

build/documents/Integral/algebra-number-theory-mixture-g11.in.tex: | \
  source/algebra/number-theory/mixture-g11.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/algebra/number-theory/mixture-g11.tex" "$@"

build/documents/Integral/geometry-triangle-inequality.in.tex: | \
  source/geometry/triangle-inequality.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/triangle-inequality.tex" "$@"

build/documents/Integral/geometry-equal-triangles-g78r2.in.tex: | \
  source/geometry/equal-triangles-g78r2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/equal-triangles-g78r2.tex" "$@"

build/documents/Integral/geometry-inequality-g78r2.in.tex: | \
  source/geometry/inequality-g78r2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/inequality-g78r2.tex" "$@"

build/documents/Integral/geometry-combinatorial-g78r2.in.tex: | \
  source/geometry/combinatorial-g78r2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/combinatorial-g78r2.tex" "$@"

build/documents/Integral/geometry-mixture-g78r1-intro.in.tex: | \
  source/geometry/mixture-g78r1-intro.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/mixture-g78r1-intro.tex" "$@"

build/documents/Integral/geometry-inscribed-angle-g78r1-1.in.tex: | \
  source/geometry/inscribed-angle-g78r1/1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/inscribed-angle-g78r1/1.tex" "$@"

build/documents/Integral/geometry-inscribed-angle-g78r1-2.in.tex: | \
  source/geometry/inscribed-angle-g78r1/2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/inscribed-angle-g78r1/2.tex" "$@"

build/documents/Integral/geometry-mixture-g78r1.in.tex: | \
  source/geometry/mixture-g78r1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/mixture-g78r1.tex" "$@"

build/documents/Integral/geometry-combinatorial-g78r1.in.tex: | \
  source/geometry/combinatorial-g78r1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/combinatorial-g78r1.tex" "$@"

build/documents/Integral/geometry-right-triangle-g9.in.tex: | \
  source/geometry/right-triangle-g9.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/right-triangle-g9.tex" "$@"

build/documents/Integral/geometry-locus-g9.in.tex: | \
  source/geometry/locus-g9.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/locus-g9.tex" "$@"

build/documents/Integral/geometry-radical-axis.in.tex: | \
  source/geometry/radical-axis.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/radical-axis.tex" "$@"

build/documents/Integral/geometry-combinatorial-g9.in.tex: | \
  source/geometry/combinatorial-g9.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/combinatorial-g9.tex" "$@"

build/documents/Integral/geometry-mixture-g1011-1.in.tex: | \
  source/geometry/mixture-g1011-1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/mixture-g1011-1.tex" "$@"

build/documents/Integral/geometry-mixture-g1011-2.in.tex: | \
  source/geometry/mixture-g1011-2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/mixture-g1011-2.tex" "$@"

build/documents/Integral/geometry-mixture-g1011-appendage.in.tex: | \
  source/geometry/mixture-g1011-appendage.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/mixture-g1011-appendage.tex" "$@"

build/documents/Integral/geometry-orthocenter-g1011.in.tex: | \
  source/geometry/orthocenter-g1011.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/orthocenter-g1011.tex" "$@"

build/documents/Integral/geometry-mass-point-1.in.tex: | \
  source/geometry/mass-point/1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/mass-point/1.tex" "$@"

build/documents/Integral/geometry-mass-point-2.in.tex: | \
  source/geometry/mass-point/2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/mass-point/2.tex" "$@"

build/documents/Integral/geometry-mass-point-3.in.tex: | \
  source/geometry/mass-point/3.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/mass-point/3.tex" "$@"

build/documents/Integral/geometry-simson-line-g10.in.tex: | \
  source/geometry/simson-line-g10.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/simson-line-g10.tex" "$@"

build/documents/Integral/geometry-euler-line-g1011.in.tex: | \
  source/geometry/euler-line/g1011.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/euler-line/g1011.tex" "$@"

build/documents/Integral/geometry-euler-line-g10.in.tex: | \
  source/geometry/euler-line/g10.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/euler-line/g10.tex" "$@"

build/documents/Integral/geometry-projective-g11-basics.in.tex: | \
  source/geometry/projective-g11/basics.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/projective-g11/basics.tex" "$@"

build/documents/Integral/geometry-projective-g11-circle.in.tex: | \
  source/geometry/projective-g11/circle.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/projective-g11/circle.tex" "$@"

build/documents/Integral/geometry-polar-line-g11.in.tex: | \
  source/geometry/polar-line-g11.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/polar-line-g11.tex" "$@"

build/documents/Integral/geometry-sparrows-1.in.tex: | \
  source/geometry/sparrows/1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/sparrows/1.tex" "$@"

build/documents/Integral/geometry-sparrows-2.in.tex: | \
  source/geometry/sparrows/2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/geometry/sparrows/2.tex" "$@"

build/documents/Integral/combinatorics-search-g78r2.in.tex: | \
  source/combinatorics/search-g78r2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/search-g78r2.tex" "$@"

build/documents/Integral/combinatorics-weighing-g78r2.in.tex: | \
  source/combinatorics/weighing-g78r2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/weighing-g78r2.tex" "$@"

build/documents/Integral/combinatorics-algorithm-g78r2.in.tex: | \
  source/combinatorics/algorithm-g78r2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/algorithm-g78r2.tex" "$@"

build/documents/Integral/combinatorics-counting-g78r2-1.in.tex: | \
  source/combinatorics/counting-g78r2/1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/counting-g78r2/1.tex" "$@"

build/documents/Integral/combinatorics-counting-g78r2-2.in.tex: | \
  source/combinatorics/counting-g78r2/2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/counting-g78r2/2.tex" "$@"

build/documents/Integral/combinatorics-inclusion-exclusion-g78r2.in.tex: | \
  source/combinatorics/inclusion-exclusion-g78r2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/inclusion-exclusion-g78r2.tex" "$@"

build/documents/Integral/combinatorics-logic-g78r2.in.tex: | \
  source/combinatorics/logic-g78r2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/logic-g78r2.tex" "$@"

build/documents/Integral/combinatorics-mixture-g78r2.in.tex: | \
  source/combinatorics/mixture-g78r2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/mixture-g78r2.tex" "$@"

build/documents/Integral/combinatorics-extreme-principle-g78r2.in.tex: | \
  source/combinatorics/extreme-principle-g78r2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/extreme-principle-g78r2.tex" "$@"

build/documents/Integral/combinatorics-game-g78r1-joke.in.tex: | \
  source/combinatorics/game-g78r1/joke.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/game-g78r1/joke.tex" "$@"

build/documents/Integral/combinatorics-game-g78r1-symmetry.in.tex: | \
  source/combinatorics/game-g78r1/symmetry.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/game-g78r1/symmetry.tex" "$@"

build/documents/Integral/combinatorics-game-g78r1-sum.in.tex: | \
  source/combinatorics/game-g78r1/sum.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/game-g78r1/sum.tex" "$@"

build/documents/Integral/combinatorics-game-g78r1-chase.in.tex: | \
  source/combinatorics/game-g78r1/chase.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/game-g78r1/chase.tex" "$@"

build/documents/Integral/combinatorics-game-g78r1-win-position.in.tex: | \
  source/combinatorics/game-g78r1/win-position.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/game-g78r1/win-position.tex" "$@"

build/documents/Integral/combinatorics-game-g78r1-mixture.in.tex: | \
  source/combinatorics/game-g78r1/mixture.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/game-g78r1/mixture.tex" "$@"

build/documents/Integral/combinatorics-weighing-g78r1.in.tex: | \
  source/combinatorics/weighing-g78r1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/weighing-g78r1.tex" "$@"

build/documents/Integral/combinatorics-information-g78r1.in.tex: | \
  source/combinatorics/information-g78r1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/information-g78r1.tex" "$@"

build/documents/Integral/combinatorics-painting-g9.in.tex: | \
  source/combinatorics/painting-g9.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/painting-g9.tex" "$@"

build/documents/Integral/combinatorics-invariant-g9.in.tex: | \
  source/combinatorics/invariant-g9.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/invariant-g9.tex" "$@"

build/documents/Integral/combinatorics-semi-invariant-g9.in.tex: | \
  source/combinatorics/semi-invariant-g9.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/semi-invariant-g9.tex" "$@"

build/documents/Integral/combinatorics-constructive-g9.in.tex: | \
  source/combinatorics/constructive-g9.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/constructive-g9.tex" "$@"

build/documents/Integral/combinatorics-infinity-g9-1.in.tex: | \
  source/combinatorics/infinity-g9/1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/infinity-g9/1.tex" "$@"

build/documents/Integral/combinatorics-infinity-g9-2.in.tex: | \
  source/combinatorics/infinity-g9/2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/infinity-g9/2.tex" "$@"

build/documents/Integral/combinatorics-game-g9.in.tex: | \
  source/combinatorics/game-g9.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/game-g9.tex" "$@"

build/documents/Integral/combinatorics-geometric-g9.in.tex: | \
  source/combinatorics/geometric-g9.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/geometric-g9.tex" "$@"

build/documents/Integral/combinatorics-recurrent-g10-loop.in.tex: | \
  source/combinatorics/recurrent-g10/loop.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/recurrent-g10/loop.tex" "$@"

build/documents/Integral/combinatorics-recurrent-g10-one-dimension.in.tex: | \
  source/combinatorics/recurrent-g10/one-dimension.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/recurrent-g10/one-dimension.tex" "$@"

build/documents/Integral/combinatorics-recurrent-g10-fibbonaci.in.tex: | \
  source/combinatorics/recurrent-g10/fibbonaci.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/recurrent-g10/fibbonaci.tex" "$@"

build/documents/Integral/combinatorics-recurrent-g10-binomial.in.tex: | \
  source/combinatorics/recurrent-g10/binomial.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/recurrent-g10/binomial.tex" "$@"

build/documents/Integral/combinatorics-recurrent-g10-catalan.in.tex: | \
  source/combinatorics/recurrent-g10/catalan.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/recurrent-g10/catalan.tex" "$@"

build/documents/Integral/combinatorics-game-g1011.in.tex: | \
  source/combinatorics/game-g1011.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/game-g1011.tex" "$@"

build/documents/Integral/combinatorics-semi-invariant-g1011.in.tex: | \
  source/combinatorics/semi-invariant-g1011.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/semi-invariant-g1011.tex" "$@"

build/documents/Integral/combinatorics-counting-g1011.in.tex: | \
  source/combinatorics/counting-g1011.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/counting-g1011.tex" "$@"

build/documents/Integral/combinatorics-game-g11.in.tex: | \
  source/combinatorics/game-g11.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/game-g11.tex" "$@"

build/documents/Integral/combinatorics-invariant-g11.in.tex: | \
  source/combinatorics/invariant-g11.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/invariant-g11.tex" "$@"

build/documents/Integral/combinatorics-semi-invariant-g11.in.tex: | \
  source/combinatorics/semi-invariant-g11.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/semi-invariant-g11.tex" "$@"

build/documents/Integral/combinatorics-graph-g78r2-basics.in.tex: | \
  source/combinatorics/graph/g78r2/basics.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/graph/g78r2/basics.tex" "$@"

build/documents/Integral/combinatorics-graph-g78r2-bipartite.in.tex: | \
  source/combinatorics/graph/g78r2/bipartite.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/graph/g78r2/bipartite.tex" "$@"

build/documents/Integral/combinatorics-graph-g78r2-oriented.in.tex: | \
  source/combinatorics/graph/g78r2/oriented.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/graph/g78r2/oriented.tex" "$@"

build/documents/Integral/combinatorics-graph-g1011-mixture.in.tex: | \
  source/combinatorics/graph/g1011/mixture.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/graph/g1011/mixture.tex" "$@"

build/documents/Integral/combinatorics-graph-g1011-oriented.in.tex: | \
  source/combinatorics/graph/g1011/oriented.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/graph/g1011/oriented.tex" "$@"

build/documents/Integral/combinatorics-graph-planar.in.tex: | \
  source/combinatorics/graph/planar.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/graph/planar.tex" "$@"

build/documents/Integral/combinatorics-graph-painting-1.in.tex: | \
  source/combinatorics/graph/painting/1.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/graph/painting/1.tex" "$@"

build/documents/Integral/combinatorics-graph-painting-2.in.tex: | \
  source/combinatorics/graph/painting/2.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/graph/painting/2.tex" "$@"

build/documents/Integral/combinatorics-graph-mixture-g11.in.tex: | \
  source/combinatorics/graph/mixture-g11.tex \
  build/documents/Integral
	ln --symbolic --force "../../../source/combinatorics/graph/mixture-g11.tex" "$@"